/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrental;


import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTextField;
/**
 *
 * @author mohana
 */
public class BOOKRENTAL extends javax.swing.JFrame {

     public Connection conn;
    public PreparedStatement pst,pst1, pst11,pst22, pst33,pst44,pst55,pst66,pst77,pst88;
    public ResultSet res,res1;
    public int id,id1,cust_id,id33,id44,id55,id66,id77,id88,numberofweeks;
    public long diff;
    public Date date1,date2;
    public boolean check;
    public float f33,f44,f55,f66,f77,f88,def;
    /**
     * Creates new form BOOKRENTAL
     */
    public BOOKRENTAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BOOK A NEW RENTAL");

        jLabel2.setText("TYPE");

        jLabel3.setText("START DATE");

        jLabel4.setText("END DATE");

        jButton1.setText("RENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPACT", "MEDIUM", "LARGE", "SUV", "TRUCK", "VAN" }));

        jLabel5.setText("CUSTOMER ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))))
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            
       
        date1 = jDateChooser1.getDate();
        date2= jDateChooser2.getDate();
         //diff=date1.getTime()-date2.getTime();
        //diff=-1;
        diff = Math.round((date2.getTime() - date1.getTime()) / (double) 86400000);
        if(diff>=7)
        {
            def= diff/7;
            System.out.println();
            numberofweeks =Math.round(diff/7);
           
        }
        //JOptionPane.showMessageDialog(null,diff);
       
        conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/CARRENTAL?user=root&password=Password");
        String sql1;
         String s=(String) jComboBox1.getSelectedItem();
            sql1 = "select VEHICLE_ID from CAR where TYPE='"+s+"'";
        pst= conn.prepareStatement(sql1);
        
        
       // pst.setInt(1, 0);
        //pst.setString(1,s);
        JOptionPane.showMessageDialog(null,sql1);
        
        res1= pst.executeQuery(sql1);
        
        while(res1.next())
        {
            id= res1.getInt("VEHICLE_ID");
        }
        System.out.println(id);
        if(diff>=7){
            check=true;
        String type="WEEKLY";
        String sql2="insert into RENTAL (R_LOC,TYPE) values(?,?)";
        pst=conn.prepareStatement(sql2);
        String city="arlington";
        pst.setString(1, city);
        pst.setString(2, type);
        pst.executeUpdate();
        String sql4="select max(R_ID) as lid1 from RENTAL";
        pst1= conn.prepareStatement(sql4);
         res1= pst.executeQuery(sql4);
        while(res1.next())
        {
            id1= res1.getInt("lid1");
        }
        
        String sql3="insert into WEEKLY_RENTAL(R_ID,NO_OF_WEEKS,START_DATE,END_DATE) values(?,?,?,?)";
        pst=conn.prepareStatement(sql3);
        pst.setInt(1, id1);
        pst.setInt(2,numberofweeks);
        java.sql.Date s_Date = new java.sql.Date(date1.getTime()); 
        pst.setDate(3, s_Date);
        java.sql.Date s_Date1 = new java.sql.Date(date2.getTime()); 
        pst.setDate(4, s_Date1);
        pst.executeUpdate();
        
        
        
        
        }
        if(diff<7){
            check=false;
        String type="DAILY";
        String sql3="insert into RENTAL (R_LOC,TYPE) values(?,?)";
        pst11=conn.prepareStatement(sql3);
        pst11.setString(1, "ARLINGTON");
        pst11.setString(2, type);
        pst11.executeUpdate();
        String sql4="select max(R_ID) as lid from RENTAL";
        pst11= conn.prepareStatement(sql4);
         res= pst.executeQuery(sql4);
        while(res.next())
        {
            id1= res.getInt("lid");
        }
        
        String sql5="insert into DAILY_RENTAL(R_ID,NO_OF_DAYS,START_DATE,END_DATE) values(?,?,?,?)";
        pst11=conn.prepareStatement(sql5);
        pst11.setInt(1, id1);
        pst11.setInt(2, (int) diff);
        java.sql.Date s_Date = new java.sql.Date(date1.getTime()); 
        pst11.setDate(3, s_Date);
        java.sql.Date s_Date1 = new java.sql.Date(date2.getTime()); 
        pst11.setDate(4, s_Date1);
        pst11.executeUpdate();
         
            
        
        
        
        } 
        String sql8="insert into RENTS (RENTAL_ID,CUSTOMER_ID,VEHICLE_ID) values(?,?,?)";
        pst22=conn.prepareStatement(sql8);
        pst22.setInt(1,id1);
         cust_id=Integer.parseInt(jTextField1.getText());
        pst22.setInt(2,cust_id);
        pst22.setInt(3,id);
        pst22.executeUpdate();
        
        
        //GENERATING BILL
        if(check=true)
        {
            
        
        if(s.equalsIgnoreCase("COMPACT"))
                    {
                        
                        
                        
                        String query = "SELECT WEEKLY_RATE as wr FROM COMPACT";
                        pst33 = conn.prepareStatement(query);
                          res= pst.executeQuery(query);
        while(res.next())
        {
            f33= res.getInt("wr");
           
        }
        float cost=f33*numberofweeks;
        System.out.println(cost);
        System.out.println(f33);
        System.out.println(numberofweeks);
        
                       
                        
                    }
        }
                   /* else if (s.equalsIgnoreCase("MEDIUM"))
                    {
                        String query = "UPDATE MEDIUM set WEEKLY_RATE=?, DAILY_RATE=?";
                        pst3 = conn.prepareStatement(query);
                        pst3.setFloat(1, f1);
                        pst3.setFloat(2,f2);
                        pst3.executeUpdate();
                    }
                    else if (s.equalsIgnoreCase("LARGE"))
                    {
                        String query = "UPDATE LARGE set WEEKLY_RATE=?, DAILY_RATE=?";
                        pst3 = conn.prepareStatement(query);
                        pst3.setFloat(1, f1);
                        pst3.setFloat(2,f2);
                        pst3.executeUpdate();
                    }
                    else if (s.equalsIgnoreCase("SUV"))
                    {
                        String query = "UPDATE SUV set WEEKLY_RATE=?, DAILY_RATE=?";
                        pst3 = conn.prepareStatement(query);
                        pst3.setFloat(1, f1);
                        pst3.setFloat(2,f2);
                        pst3.executeUpdate();
                    }
                    else if (s.equalsIgnoreCase("VAN"))
                    {
                        String query = "UPDATE VAN set WEEKLY_RATE=?, DAILY_RATE=?";
                        pst3 = conn.prepareStatement(query);
                        pst3.setFloat(1, f1);
                        pst3.setFloat(2,f2);
                        pst3.executeUpdate();
                    }
                    else
                    {
                        String query = "UPDATE TRUCK set WEEKLY_RATE=?, DAILY_RATE=?";
                        pst3 = conn.prepareStatement(query);
                        pst3.setFloat(1, f1);
                        pst3.setFloat(2,f2);
                        pst3.executeUpdate();
                    }*/
        
    }   
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOKRENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOKRENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOKRENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOKRENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOOKRENTAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
